### ISSUE TITLE
does not work with webpack2

### ISSUE THREAD

**Issue by netchkin** [clementprevot/webpack-validator#1]
upon entering the following config for webpack@2.2.0:
```
{
  entry: path.resolve(__dirname, 'src/index.js'),
  output: {
    path: path.resolve(__dirname, outputDir),
    filename: 'frontend.bundle.js'
  },
  target: 'web',
  module: {
    rules: [
      { test: '/.jsx$/', use: 'babel-loader' }
    ]
  }
}
```
according to the [official docs](https://webpack.js.org/concepts/loaders/), this should be a valid configuration, yet the validation produces the following output:

> [1] "loaders" is required
> [2] "rules" is not allowed

**Comment by clementprevot** [comment]
This package is not maintened anymore as config validation is natively available in webpack2
